### ISSUE TITLE
Issue with librex

### ISSUE THREAD

**Issue by nullthreat** [mubix/whitechapel-ng#3]
librex
  text.rb file
    line 609 and 611 needs new regex format

**Comment by mubix** [comment]
What's the issue? And when does that error happen?

**Comment by nullthreat** [comment]
When loading rex in rails the error:

```
SyntaxError: /Users/elliottcutright/.gem/ruby/2.0.0/bundler/gems/rex-0267700d0bc5/lib/rex/text.rb:609: invalid multibyte escape: /([\x00-\x20\x80-\xFF])/
```

**Comment by nullthreat** [comment]
Works fine in ruby 2 outside of rails 

```
[1] pry(main)> require 'rex'
=> true
```

**Comment by mubix** [comment]
librex supports 1.9.2 and above only as far as I know

**Comment by nullthreat** [comment]
You have a note about replacing rex with openssl, is that possible?

**Comment by mubix** [comment]
don't think so, but its possible if we just steal the methods out of librex

**Comment by nullthreat** [comment]
thats what im going to try now

**Comment by nullthreat** [comment]
looks like we can just do 

```
require 'rex/proto/ntlm/crypt'
```

and get the job done...testing

**Comment by nullthreat** [comment]
Worked for lm, failed on ntlm. ntlm needs rex/text which is the offending part of rex

**Comment by nullthreat** [comment]
Commented out offending function in librex, moving forward with rest of formats to see if it works

**Comment by nullthreat** [comment]
Fixed
